ECommerce.MvcWebUI/Areas/Admin/Controllers/CustomerController.cs
using ECommerce.Business.Abstract;
using ECommerce.Entities.ComplexTypes;
using ECommerce.Entities.Concrete;
using ECommerce.MvcWebUI.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.MvcWebUI.Areas.Admin.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly ICityService _cityService;
        private readonly IDistrictService _districtService;
        private readonly IAddressService _addressService;
        private readonly IOrderService _orderService;
        public CustomerController(ICustomerService customerService, ICityService cityService, IDistrictService districtService, IAddressService addressService, IOrderService orderService)
        {
            _customerService = customerService;
            _cityService = cityService;
            _districtService = districtService;
            _addressService = addressService;
            _orderService = orderService;
        }

        public ActionResult Index()
        {
            var customerList = _customerService.GetListWithCityName();
            return View(customerList);
        }

        public ActionResult Form()
        {
            ViewBag.Title = "Müşteri Ekle";
            CustomerItem customerItem = new CustomerItem()
            {
                Customer = null,
                Cities = _cityService.GetList(),
                Districts = _districtService.GetList(x => x.CityId == 0)
            };
            return View("Form", customerItem);
        }

        public ActionResult Update(int id)
        {
            if (id > 0)
            {
                var customer = _customerService.Get(c => c.Id == id);
                if (customer != null)
                {
                    ViewBag.Title = "Müşteri Güncelle";
                    CustomerItem customerItem = new CustomerItem()
                    {
                        Customer = customer,
                        Cities = _cityService.GetList().OrderBy(x => customer.CityId).ToList(),
                        Districts = _districtService.GetList().Where(x => x.CityId == customer.CityId).OrderBy(x => customer.DistrictId).ToList()
                    };
                    return View("Form", customerItem);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form(CustomerItem customerItem)
        {
            var customer = customerItem.Customer;

            if (customer.Id == 0)
            {
                ViewBag.Title = "Müşteri Ekle";
                try
                {
                    _customerService.Add(customer);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = customer.FirstName + " " + customer.LastName, Message = "ad soyadlı müşteri eklendi...", LinkText = "Müşteri Listesi", Url = "/Admin/Customer" };
                    ModelState.Clear();
                    return RedirectToAction("Form");
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                    CustomerItem customerNew = new CustomerItem()
                    {
                        Customer = customerItem.Customer,
                        Cities = _cityService.GetList(x => x.Id == customer.CityId),
                        Districts = _districtService.GetList(x => x.Id == customer.DistrictId)
                    };
                    return View("Form", customerNew);
                }                
            }
            else
            {
                try
                {
                    _customerService.Update(customer);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = customer.FirstName + " " + customer.LastName, Message = "ad soyadlı müşteri güncellendi...", LinkText = "Müşteri Listesi", Url = "/Admin/Customer" };
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                }
                return RedirectToAction("Update", new { id = customer.Id });
            }
        }

        public ActionResult Address(int id)
        {
            var customer = _customerService.Get(x => x.Id == id);
            if (customer != null)
            {
                var addressList = _addressService.GetListWithCityNameAndDistrictName(id);
                return View(addressList);
            }
            return RedirectToAction("Index");
        }

        public ActionResult AddressForm(int id)
        {
            var customer = _customerService.Get(x => x.Id == id);
            if (customer != null)
            {
                ViewBag.Title = "Adres Ekle";
                CustomerAddressItem customerAddressItem = new CustomerAddressItem()
                {
                    Address = new Address { CustomerId = id },
                    Cities = _cityService.GetList(),
                    Districts = _districtService.GetList(x => x.CityId == 0)
                };
                return View("AddressForm", customerAddressItem);
            }
            return RedirectToAction("Index");
        }

        public ActionResult UpdateAddress(int id)
        {
            if (id > 0)
            {
                var customerAddress = _addressService.Get(c => c.Id == id);
                if (customerAddress != null)
                {
                    ViewBag.Title = "Adres Güncelle";
                    CustomerAddressItem customerAddressItem = new CustomerAddressItem()
                    {
                        Address = customerAddress,
                        Cities = _cityService.GetList().OrderBy(x => customerAddress.CityId).ToList(),
                        Districts = _districtService.GetList().Where(x => x.CityId == customerAddress.CityId).OrderBy(x => customerAddress.DistrictId).ToList()
                    };
                    return View("AddressForm", customerAddressItem);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddressForm(CustomerAddressItem customerAddressItem)
        {            
            var address = customerAddressItem.Address;

            if (address.Id == 0)
            {
                ViewBag.Title = "Adres Ekle";
                try
                {
                    _addressService.Add(address);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = address.AddressName, Message = "başlıklı adres eklendi...", LinkText = "Adres Listesi", Url = "/Admin/Customer/Address/" + address.CustomerId };
                    ModelState.Clear();
                    return RedirectToAction("AddressForm");
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                    CustomerAddressItem customerAddressNew = new CustomerAddressItem()
                    {
                        Address = address,
                        Cities = _cityService.GetList(x => x.Id == address.CityId),
                        Districts = _districtService.GetList(x => x.Id == address.DistrictId)
                    };
                    return View("AddressForm", customerAddressNew);
                }
            }
            else
            {
                try
                {
                    _addressService.Update(address);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = address.AddressName, Message = "başlıklı adres güncellendi...", LinkText = "Adres Listesi", Url = "/Admin/Customer/Address/" + address.CustomerId };
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                }
                return RedirectToAction("UpdateAddress", new { id = address.Id });
            }
        }

        public ActionResult Order(int id)
        {
            var customer = _customerService.Get(c => c.Id == id);
            if (customer != null)
            {
                var orderList = _orderService.GetListWithProductName(id);
                return View(orderList);
            }
            return RedirectToAction("Index");
        }

        public ActionResult UpdateOrder(int id)
        {
            if (id > 0)
            {
                var customerOrder = _orderService.Get(c => c.Id == id);
                if (customerOrder != null)
                {
                    ViewBag.Title = "Sipariş Güncelle";
                    CustomerOrderItem customerOrderItem = new CustomerOrderItem()
                    {
                        Order = customerOrder,
                        Addresses = _addressService.GetList(c => c.CustomerId == customerOrder.CustomerId).ToList(),
                        OrderStatuses = _orderService.GetOrderList().ToList()
                    };
                    return View("OrderForm", customerOrderItem);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OrderForm(CustomerOrderItem customerOrderItem)
        {
            var order = customerOrderItem.Order;
            if (order != null)
            {
                try
                {

ECommerce.MvcWebUI/Areas/Admin/Controllers/OrderController.cs
using ECommerce.Business.Abstract;
using ECommerce.Entities.ComplexTypes;
using ECommerce.MvcWebUI.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.MvcWebUI.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IAddressService _addressService;
        private readonly ICustomerService _customerService;
        private readonly IProductService _productService;
        public OrderController(IOrderService orderService, IAddressService addressService, ICustomerService customerService, IProductService productService)
        {
            _orderService = orderService;
            _addressService = addressService;
            _customerService = customerService;
            _productService = productService;
        }

        public ActionResult Index()
        {
            var orderList = _orderService.GetListWithProductNameAndCustomerName();
            return View(orderList);
        }

        public ActionResult Form(int id)
        {
            if (id > 0)
            {
                var order = _orderService.Get(o => o.Id == id);
                if (order != null)
                {
                    ViewBag.Title = "Sipariş Güncelle";
                    OrderItem orderItem = new OrderItem()
                    {
                        ProductName = _productService.Get(p => p.Id == order.ProductId).ProductName,
                        CustomerFullName = _customerService.Get(c => c.Id == order.CustomerId).FirstName + " " + _customerService.Get(c => c.Id == order.CustomerId).LastName,
                        Order = order,
                        Addresses = _addressService.GetList(o => o.CustomerId == order.CustomerId).ToList(),
                        OrderStatuses = _orderService.GetOrderList().ToList()
                    };
                    return View("Form", orderItem);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form(OrderItem orderItem)
        {
            var order = orderItem.Order;
            if (order != null)
            {
                try
                {
                    _orderService.Update(order);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = order.Id.ToString(), Message = " nolu sipariş bilgisi güncellendi...", LinkText = "Sipariş Listesi", Url = "/Admin/Order" };
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                }
                return RedirectToAction("Form", new { id = order.Id });
            }
            return RedirectToAction("Index");
        }
    }
}

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/Address.cshtml
@using ECommerce.Entities.ComplexTypes
@model List<CustomerAddressItem>
@{
    ViewBag.Title = "Müşteri Adresleri";
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">Müşteri Adres Listesi</h1>
</div>

<div class="pt-3 pb-2 mb-3">
    <a href="@Url.Action("AddressForm", "Customer", new { id = Url.RequestContext.RouteData.Values["id"] })" class="btn btn-success"><i class="fa fa-plus"></i> Yeni Adres</a>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Adres Başlığı</th>
            <th>Şehir</th>
            <th>İlçe</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customerAddress in Model)
        {
            <tr>
                <td>@customerAddress.Address.AddressName</td>
                <td>@customerAddress.CityName</td>
                <td>@customerAddress.DistrictName</td>
                <td>
                    @Html.ActionLink("Güncelle", "UpdateAddress", null, new { id = customerAddress.Address.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/AddressForm.cshtml
@using ECommerce.Entities.ComplexTypes
@model CustomerAddressItem
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">@ViewBag.Title</h1>
</div>

@if (TempData["Message"] != null)
{
    var message = (ECommerce.MvcWebUI.Areas.Admin.ViewModels.MessageViewModel)TempData["Message"];
    <div class="alert @message.CssClass alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>@message.Title</strong> @message.Message <a href="@message.Url">@message.LinkText</a>
    </div>
}

@using (Html.BeginForm("AddressForm", "Customer", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(c => c.Address.AddressName)
        @Html.TextBoxFor(c => c.Address.AddressName, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Address.AddressName, "", new { @class = "text-danger" })
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Address.CityId)
                @Html.DropDownListFor(c => c.Address.CityId, new SelectList(Model.Cities, "Id", "CityName"), "İl Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Address.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Address.DistrictId)
                @Html.DropDownListFor(c => c.Address.DistrictId, new SelectList(Model.Districts, "Id", "DistrictName"), "İlçe Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Address.DistrictId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Address.AddressContent)
        @Html.TextBoxFor(c => c.Address.AddressContent, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Address.AddressContent, "", new { @class = "text-danger" })
    </div>
    <div class="form-group mt-3">
        @Html.HiddenFor(c => c.Address.Id)
        @Html.HiddenFor(c => c.Address.CustomerId)
        <button type="submit" class="btn btn-info">Kaydet</button>
    </div>
}

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/Form.cshtml
@using ECommerce.Entities.ComplexTypes
@model CustomerItem
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">@ViewBag.Title</h1>
</div>

@if (TempData["Message"] != null)
{
    var message = (ECommerce.MvcWebUI.Areas.Admin.ViewModels.MessageViewModel)TempData["Message"];
    <div class="alert @message.CssClass alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>@message.Title</strong> @message.Message <a href="@message.Url">@message.LinkText</a>
    </div>
}

@using (Html.BeginForm("Form", "Customer", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.FirstName)
                @Html.TextBoxFor(c => c.Customer.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.LastName)
                @Html.TextBoxFor(c => c.Customer.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.IdentificationNumber)
                @Html.TextBoxFor(c => c.Customer.IdentificationNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.IdentificationNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.DateOfBirth)
                @Html.TextBoxFor(c => c.Customer.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(c => c.Customer.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.Email)
                @Html.TextBoxFor(c => c.Customer.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.Password)
                @if (Model.Customer != null)
                {
                    @Html.PasswordFor(c => c.Customer.Password, new { @class = "form-control", @value = Model.Customer.Password })
                }
                else
                {
                    @Html.PasswordFor(c => c.Customer.Password, new { @class = "form-control" })
                }
                @Html.ValidationMessageFor(c => c.Customer.Password, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.CityId)
                @Html.DropDownListFor(c => c.Customer.CityId, new SelectList(Model.Cities, "Id", "CityName"), "İl Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Customer.DistrictId)
                @Html.DropDownListFor(c => c.Customer.DistrictId, new SelectList(Model.Districts, "Id", "DistrictName"), "İlçe Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Customer.DistrictId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.Address)
        @Html.TextBoxFor(c => c.Customer.Address, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Customer.Address, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Customer.Phone)
        @Html.TextBoxFor(c => c.Customer.Phone, new { @class = "form-control" })
    </div>
    <div class="form-group mt-3">
        @Html.HiddenFor(c => c.Customer.Id)
        @Html.HiddenFor(c => c.Customer.DateOfRegistration)
        <button type="submit" class="btn btn-info">Kaydet</button>
    </div>
}

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/Index.cshtml
@using ECommerce.Entities.ComplexTypes
@model List<CustomerItem>
@{
    ViewBag.Title = "Müşteriler";
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">Müşteri Listesi</h1>
</div>

<div class="pt-3 pb-2 mb-3">
    <a href="@Url.Action("Form", "Customer")" class="btn btn-success"><i class="fa fa-plus"></i> Yeni Müşteri</a>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Ad Soyad</th>
            <th>Yaş</th>
            <th>E-mail</th>
            <th>Şehir</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.Customer.FirstName @customer.Customer.LastName</td>
                <td>
                    @if (customer.Customer.DateOfBirth != null)
                    {
                        @(DateTime.Now.Year - customer.Customer.DateOfBirth.Value.Year)
                    }
                    else
                    {
                        <span>-</span>
                    }
                </td>
                <td>@customer.Customer.Email</td>
                <td>@customer.CityName</td>
                <td>
                    @Html.ActionLink("Adresler", "Address", null, new { id = customer.Customer.Id }, new { @class = "btn btn-dark" })
                    @Html.ActionLink("Siparişler", "Order", null, new { id = customer.Customer.Id }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Güncelle", "Update", null, new { id = customer.Customer.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/Order.cshtml
@using ECommerce.Entities.ComplexTypes
@model List<CustomerOrderItem>
@{
    ViewBag.Title = "Müşteri Siparişleri";
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">Müşteri Sipariş Listesi</h1>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Ürün</th>
            <th>Sipariş Tarihi</th>
            <th>Teslim Tarihi</th>
            <th>Sipariş Durumu</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customerOrder in Model)
        {
            <tr>
                <td>@customerOrder.ProductName</td>
                <td>@customerOrder.Order.OrderDate.ToString("dd.MM.yyyy")</td>
                <td>
                    @if (customerOrder.Order.DeliveryDate != null)
                    {
                        @customerOrder.Order.DeliveryDate.Value.ToString("dd.MM.yyyy")
                    }
                    else
                    {
                        <code>Belirtilmemiş</code>
                    }
                </td>
                <td>
                    @if (customerOrder.OrderStatus == "Gönderildi")
                    {
                        <h6><span class="badge badge-success">@customerOrder.OrderStatus</span></h6>
                    }
                    else if (customerOrder.OrderStatus == "Kargoda")
                    {
                        <h6><span class="badge badge-warning">@customerOrder.OrderStatus</span></h6>
                    }
                    else if (customerOrder.OrderStatus == "İptal Edildi")
                    {
                        <h6><span class="badge badge-danger">@customerOrder.OrderStatus</span></h6>
                    }
                    else
                    {
                        <h6><span class="badge badge-light">@customerOrder.OrderStatus</span></h6>
                    }
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "UpdateOrder", null, new { id = customerOrder.Order.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>

ECommerce.MvcWebUI/Areas/Admin/Views/Customer/OrderForm.cshtml
@using ECommerce.Entities.ComplexTypes
@model CustomerOrderItem
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">@ViewBag.Title</h1>
</div>

@if (TempData["Message"] != null)
{
    var message = (ECommerce.MvcWebUI.Areas.Admin.ViewModels.MessageViewModel)TempData["Message"];
    <div class="alert @message.CssClass alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>@message.Title</strong> @message.Message <a href="@message.Url">@message.LinkText</a>
    </div>
}

@using (Html.BeginForm("OrderForm", "Customer", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Order.OrderStatusId)
                @Html.DropDownListFor(c => c.Order.OrderStatusId, new SelectList(Model.OrderStatuses, "Id", "Status"), new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Order.OrderStatusId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Order.AddressId)
                @Html.DropDownListFor(c => c.Order.AddressId, new SelectList(Model.Addresses, "Id", "AddressName"), new { @class = "form-control" })
                @Html.ValidationMessageFor(c => c.Order.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Order.OrderDate)
                @Html.TextBoxFor(c => c.Order.OrderDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date", @readonly = "readonly" })
                @Html.ValidationMessageFor(c => c.Order.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(c => c.Order.DeliveryDate)
                @Html.TextBoxFor(c => c.Order.DeliveryDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(c => c.Order.DeliveryDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group mt-3">
        @Html.HiddenFor(c => c.Order.Id)
        @Html.HiddenFor(c => c.Order.CustomerId)
        @Html.HiddenFor(c => c.Order.ProductId)
        <button type="submit" class="btn btn-info">Kaydet</button>
    </div>
}