ECommerce.MvcWebUI/Areas/Admin/Controllers/BrandController.cs
using ECommerce.Business.Abstract;
using ECommerce.Entities.Concrete;
using ECommerce.MvcWebUI.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.MvcWebUI.Areas.Admin.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;
        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public ActionResult Index()
        {
            var brandList = _brandService.GetList();
            return View(brandList);
        }

        public ActionResult Form()
        {
            ViewBag.Title = "Marka Ekle";
            return View("Form");
        }

        public ActionResult Update(int id)
        {
            if (id > 0)
            {
                var brand = _brandService.Get(b => b.Id == id);
                if (brand != null)
                {
                    ViewBag.Title = "Marka Güncelle";
                    return View("Form", brand);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form(Brand brand)
        {
            if (brand.Id == 0)
            {
                ViewBag.Title = "Marka Ekle";
                try
                {
                    _brandService.Add(brand);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = brand.BrandName, Message = "adlı marka eklendi...", LinkText = "Marka Listesi", Url = "/Admin/Brand" };
                    ModelState.Clear();
                    return View("Form");
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                    return View("Form", brand);
                }
            }
            else
            {
                try
                {
                    _brandService.Update(brand);
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-success", Title = brand.BrandName, Message = "adlı marka güncellendi...", LinkText = "Marka Listesi", Url = "/Admin/Brand" };
                }
                catch (Exception ex)
                {
                    TempData["Message"] = new MessageViewModel() { CssClass = "alert-danger", Title = "", Message = ex.Message };
                }
                return RedirectToAction("Update", new { id = brand.Id });
            }
        }
    }
}

ECommerce.MvcWebUI/Areas/Admin/Views/Brand/Form.cshtml
@using ECommerce.Entities.Concrete
@model Brand
@{
    ViewBag.Title = ViewBag.Title;
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">@ViewBag.Title</h1>
</div>

@if (TempData["Message"] != null)
{
    var message = (ECommerce.MvcWebUI.Areas.Admin.ViewModels.MessageViewModel)TempData["Message"];
    <div class="alert @message.CssClass alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>@message.Title</strong> @message.Message <a href="@message.Url">@message.LinkText</a>
    </div>
}

@using (Html.BeginForm("Form", "Brand", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(b => b.BrandName)
        @Html.TextBoxFor(b => b.BrandName, new { @class = "form-control" })
        @Html.ValidationMessageFor(b => b.BrandName, "", new { @class = "text-danger" })
    </div>
    <div class="form-check form-check-inline">
        @Html.CheckBoxFor(b => b.IsActive, new { @class = "form-check-input" })
        @Html.LabelFor(b => b.IsActive, "Marka aktifse seçiniz", new { @class = "form-check-label" })
    </div>
    <div class="form-group mt-3">
        @Html.HiddenFor(b => b.Id)
        <button type="submit" class="btn btn-info">Kaydet</button>
    </div>
}

ECommerce.MvcWebUI/Areas/Admin/Views/Brand/Index.cshtml
@using ECommerce.Entities.Concrete
@model List<Brand>

@{
    ViewBag.Title = "Markalar";
    Layout = "~/Areas/Admin/Views/Shared/_Layaout.cshtml";
}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h1 class="h2">Marka Listesi</h1>
</div>

<div class="pt-3 pb-2 mb-3">
    <a href="@Url.Action("Form", "Brand")" class="btn btn-success"><i class="fa fa-plus"></i> Yeni Marka</a>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Marka Adı</th>
            <th>Durum</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var brand in Model)
        {
            <tr>
                <td>@brand.BrandName</td>
                <td>
                    @if (brand.IsActive)
                    {
                        <h6><span class="badge badge-success">Aktif</span></h6>
                    }
                    else
                    {
                        <h6><span class="badge badge-danger">Pasif</span></h6>
                    }
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "Update", null, new { id = brand.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>